apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootappdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootappdemo
  template:
    metadata:
      labels:
        app: springbootappdemo
    spec:
      containers:
        - name: springbootappdemo
          image: 381492031679.dkr.ecr.ap-southeast-1.amazonaws.com/spring-boot-test:latest
          ports:
            - containerPort: 8080
 
---
apiVersion: v1
kind: Service
metadata:
  name: springbootappdemo-service
spec:
  selector:
    app: springbootappdemo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer